### ISSUE TITLE
Still running pending tasks

### ISSUE THREAD

**Issue by jokiefer** [mrmap-community/mrmap#21]
# Status quo
If a pending task runs in to an error, an errorreport should be created. This happens for register wms/wfs/csw resources. However, if an async harvest task runs into an error, the error report is'nt generated by Mr. Map.

# Reproduction
1. I registered `https://gdk.gdi-de.org/gdi-de/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities` in Mr. Map.
1. I start harvest for this csw resource. 
1. The task runs into ReadTimeout exception:

```
Traceback (most recent call last):
  File "/home/jonas/Git/MrMap/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/jonas/Git/MrMap/venv/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/jonas/Git/MrMap/csw/tasks.py", line 37, in async_harvest
    harvester.harvest(task_id=async_harvest.request.id)
  File "/home/jonas/Git/MrMap/csw/utils/harvester.py", line 121, in harvest
    hits_response, status_code = self._get_harvest_response(result_type="hits")
  File "/home/jonas/Git/MrMap/csw/utils/harvester.py", line 307, in _get_harvest_response
    connector.load(params=params)
  File "/home/jonas/Git/MrMap/service/helper/common_connector.py", line 98, in load
    response = self.__load_requests(params)
  File "/home/jonas/Git/MrMap/service/helper/common_connector.py", line 201, in __load_requests
    response = requests.request(self.http_method, self._url, params=params, proxies=proxies, timeout=REQUEST_TIMEOUT)
  File "/home/jonas/Git/MrMap/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jonas/Git/MrMap/venv/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jonas/Git/MrMap/venv/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/jonas/Git/MrMap/venv/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='gdk.gdi-de.org', port=443): Read timed out. (read timeout=100)

```

# Solution
Wrap all async tasks with a try/catch block to catch all exceptions.

**Comment by jokiefer** [comment]
outdated - closed
