### ISSUE TITLE
ServiceUrl url attribute is null for some layers in wms version 1.1.0

### ISSUE THREAD

**Issue by jokiefer** [mrmap-community/mrmap#22]
# Status quo 
If we register a wms with version 1.1.0 there are some service url which doesn't containing a url. This causes problemes for example in our monitoring runs.

# Steps to reproduce
1. Registere service: http://geo5.service24.rlp.de/wms/karte_rp.fcgi?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.1.0
1. Run monitoring for this new registered service ==> Cause there are None filled url's this runs in to:
```Cannot mix str and non-str arguments
Traceback (most recent call last):
  File "/home/jonas/Git/MrMap/monitoring/tasks.py", line 69, in run_manual_monitoring
    monitor.run_checks()
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/jonas/Git/MrMap/monitoring/monitoring.py", line 70, in run_checks
    self.check_wms(check_obj)
  File "/home/jonas/Git/MrMap/monitoring/monitoring.py", line 132, in check_wms
    wms_helper.set_operation_urls()
  File "/home/jonas/Git/MrMap/monitoring/helper/wmsHelper.py", line 44, in set_operation_urls
    self.get_styles_url = self.get_get_styles_url()
  File "/home/jonas/Git/MrMap/monitoring/helper/wmsHelper.py", line 74, in get_get_styles_url
    url = UrlHelper.build(uri, queries)
  File "/home/jonas/Git/MrMap/monitoring/helper/urlHelper.py", line 41, in build
    build = parse.urlunparse((_url.scheme, _url.netloc, _url.path, _url.params, query_string, _url.fragment))
  File "/usr/lib/python3.7/urllib/parse.py", line 475, in urlunparse
    _coerce_args(*components))
  File "/usr/lib/python3.7/urllib/parse.py", line 120, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments```


`

**Comment by jokiefer** [comment]
`ServiceUrl` instances with empty `url` attribute are no longer possible since #1 is merged.

closed
