### ISSUE TITLE
Error "The requested service could not be found." when fetching current capabilities of WMS

### ISSUE THREAD

**Issue by jokiefer** [mrmap-community/mrmap#27]
Steps for reproducing:

* Add a new WMS. I used the following URL: https://www.wms.nrw.de/geobasis/wms_nw_bodenbewegungsgebiete_kacheln?&request=GetCapabilities&version=1.3.0&service=WMS
* Click "Activate"
* Click "Capabilities" -> "Current"

**Comment by jokiefer** [comment]
hi markus,

there seems to be a problem with wms 1.3.0. please use the 1.1.1 version and maybe you can youse following wms for testing:
https://gis.mffjiv.rlp.de/cgi-bin/mapserv?map=/data/mapserver/mapfiles/institutions_0601.map&

there are metadataurls with coupled resources and we have also a wfs interface at the same location:
https://gis.mffjiv.rlp.de/cgi-bin/mapserv?map=/data/mapserver/mapfiles/institutions_0601.map&REQUEST=GetCapabilities&VERSION=1.1.1&SERVICE=WFS

the capabilities and dataset metadata was generated by scripts:

https://gis.mffjiv.rlp.de/cgi-scripts/spatialDataList.php

**Comment by jokiefer** [comment]
Hi Armin,

thanks for your reply and the suggested test instances.

Unfortunately, I cannot just use them right now:

    We only seem to have WMS (View Service) Tests for WMS 1.3.0, so I cannot use the 1.1.1 instance
    When registering the WFS instance in MrMap I get the following error: “django.template.exceptions.TemplateDoesNotExist: includes/index/pending_task_table_refresh_script.html”

**Comment by jokiefer** [comment]
hi markus,

the problem with the wfs is new - @hollsandre will have a look ;-) .
in case of wms we only use v 1.1.1 and don’t want to mix them cause of the crs interpretation problem (lat/lon - lon/lat).
you can push the wms 1.1.1 to the inspire iso1928 test - i think that is ok for the first time - maybe we will support 1.3.0 capabilities generation in future.

i see that in the gdi-de testsuite there is a test for ST01_INSPIRE View Services - WMS 1.1.1

is this a wrapper for the old testsuite?

**Comment by jokiefer** [comment]
can't be reproduced in the current version

**Comment by jokiefer** [comment]
Traceback for this bug:

```bash
ERROR 2021-03-16 13:43:46,994 views 3727 139723920836352: Layer matching query does not exist.
Traceback (most recent call last):
  File "/home/jonas/Git/mrmap_/mrmap/service/models.py", line 1184, in get_current_capability_xml
    is_original=False,
  File "/home/jonas/Git/mrmap_/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jonas/Git/mrmap_/venv/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
service.models.Document.DoesNotExist: Document matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/Git/mrmap_/mrmap/service/views.py", line 848, in get_operation_result
    return _get_capabilities(request=request, metadata_id=metadata_id)
  File "/home/jonas/Git/mrmap_/mrmap/service/views.py", line 397, in _get_capabilities
    doc = get_resource_capabilities(request, md)
  File "/home/jonas/Git/mrmap_/mrmap/service/helper/service_helper.py", line 357, in get_resource_capabilities
    doc = md.get_current_capability_xml(version_param)
  File "/home/jonas/Git/mrmap_/mrmap/service/models.py", line 1198, in get_current_capability_xml
    cap_xml = self._create_capability_xml(version_param)
  File "/home/jonas/Git/mrmap_/mrmap/service/models.py", line 1232, in _create_capability_xml
    xml = capabilty_builder.generate_xml()
  File "/home/jonas/Git/mrmap_/mrmap/service/helper/ogc/capabilities_builder.py", line 139, in generate_xml
    xml = xml_builder._generate_xml()
  File "/home/jonas/Git/mrmap_/mrmap/service/helper/ogc/capabilities_builder.py", line 383, in _generate_xml
    self._generate_capability_xml(capability)
  File "/home/jonas/Git/mrmap_/mrmap/service/helper/ogc/capabilities_builder.py", line 1365, in _generate_capability_xml
    self._generate_capability_layer_xml(capability_elem, md)
  File "/home/jonas/Git/mrmap_/mrmap/service/helper/ogc/capabilities_builder.py", line 736, in _generate_capability_layer_xml
    metadata=md
  File "/home/jonas/Git/mrmap_/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jonas/Git/mrmap_/venv/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
service.models.Layer.DoesNotExist: Layer matching query does not exist.
```
